### ISSUE TITLE
NameError: global name 'f' is not defined

### ISSUE THREAD

**Issue by w-biggs** [tpwrules/ARCTool#3]
Attempting to run the script throws this error:

```Traceback (most recent call last):
  File "/usr/bin/ARCTool.py", line 397, in <module>
    main()
  File "/usr/bin/ARCTool.py", line 390, in main
    unu8(f, of)
  File "/usr/bin/ARCTool.py", line 320, in unu8
    dest.write(f.read(size))
NameError: global name 'f' is not defined
```

on `Python 2.7.15rc1`

**Comment by w-biggs** [comment]
Replacing the `f` in that line with `i` seems to fix the issue. I can submit a pull request tomorrow maybe...
